title: "A Statistical Physics Perspective on Machine Learning"
description: "Draft chapters and lecture notes by Florent Krzakala, Bruno Loureiro, Antoine Maillard and Lenka Zdeborova"
theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed
